language: python
python:
  - "3.6"
# Dependency intsall script
install:
  pip install -r requirements.txt
# Test script
script:
  pytest --cov=app tests/
after_success:
  coveralls
# Notification config
notifications:
  email:
    on_success: change